<?php
/**
 * DomainHub Installation Script
 * 
 * This script handles the initial setup of the application.
 * It should be deleted after successful installation for security reasons.
 */

// Disable error display in production
ini_set('display_errors', 0);
error_reporting(E_ALL);

// Check if already installed
$installLockFile = __DIR__ . '/config/install.lock';
if (file_exists($installLockFile)) {
    die('<h1>Installation Complete</h1><p>The application is already installed. If you need to reinstall, delete the config/install.lock file.</p>');
}

// Configuration file path
$configFile = __DIR__ . '/config/database.php';
$schemaFile = __DIR__ . '/sql/install_schema.sql';

// Get form data
$step = isset($_GET['step']) ? (int)$_GET['step'] : 1;
$errors = [];
$success = false;

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['step'])) {
    $step = (int)$_POST['step'];
    
    if ($step === 1) {
        // Validate database credentials
        $host = trim($_POST['db_host'] ?? '');
        $port = trim($_POST['db_port'] ?? '3306');
        $database = trim($_POST['db_name'] ?? '');
        $username = trim($_POST['db_user'] ?? '');
        $password = $_POST['db_pass'] ?? '';
        
        if (empty($host) || empty($database) || empty($username)) {
            $errors[] = 'تمامی فیلدهای اتصال به دیتابیس الزامی هستند.';
        } else {
            // Test database connection
            try {
                $dsn = "mysql:host={$host};port={$port};charset=utf8mb4";
                $pdo = new PDO($dsn, $username, $password, [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC
                ]);
                
                // Check if database exists, create if not
                $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$database}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
                $pdo->exec("USE `{$database}`");
                
                // Save configuration
                $configContent = "<?php\n/**\n * Database Configuration\n * Auto-generated by installer\n */\nreturn [\n    'host' => '" . addslashes($host) . "',\n    'port' => '" . addslashes($port) . "',\n    'database' => '" . addslashes($database) . "',\n    'username' => '" . addslashes($username) . "',\n    'password' => '" . addslashes($password) . "',\n    'charset' => 'utf8mb4',\n    'options' => [\n        PDO::ATTR_ERRMODE => PDO::ATTR_ERRMODE_EXCEPTION,\n        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,\n        PDO::ATTR_EMULATE_PREPARES => false,\n    ]\n];\n";
                
                if (file_put_contents($configFile, $configContent) !== false) {
                    $success = true;
                    $step = 2;
                } else {
                    $errors[] = 'خطا در ایجاد فایل تنظیمات. لطفا دسترسی پوشه config را بررسی کنید.';
                }
                
            } catch (PDOException $e) {
                $errors[] = 'خطا در اتصال به دیتابیس: ' . $e->getMessage();
            }
        }
    } elseif ($step === 2) {
        // Run schema installation
        try {
            if (!file_exists($configFile)) {
                throw new Exception('فایل تنظیمات دیتابیس یافت نشد.');
            }
            
            $dbConfig = require $configFile;
            $dsn = "mysql:host={$dbConfig['host']};port={$dbConfig['port']};dbname={$dbConfig['database']};charset=utf8mb4";
            $pdo = new PDO($dsn, $dbConfig['username'], $dbConfig['password'], $dbConfig['options']);
            
            // Read and execute SQL schema
            if (!file_exists($schemaFile)) {
                throw new Exception('فایل اسکیمای دیتابیس یافت نشد.');
            }
            
            $sql = file_get_contents($schemaFile);
            $statements = array_filter(array_map('trim', explode(';', $sql)));
            
            foreach ($statements as $statement) {
                if (!empty($statement) && !preg_match('/^--/', $statement)) {
                    $pdo->exec($statement);
                }
            }
            
            // Create install lock
            if (file_put_contents($installLockFile, date('Y-m-d H:i:s')) !== false) {
                $success = true;
                $step = 3;
            } else {
                $errors[] = 'خطا در ایجاد فایل قفل نصب.';
            }
            
        } catch (Exception $e) {
            $errors[] = 'خطا در نصب: ' . $e->getMessage();
        }
    }
}

?>
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>نصب DomainHub</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
        }
        
        .installer-container {
            background: white;
            border-radius: 20px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            max-width: 600px;
            width: 100%;
            overflow: hidden;
            animation: slideIn 0.5s ease-out;
        }
        
        @keyframes slideIn {
            from {
                opacity: 0;
                transform: translateY(30px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }
        
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px 30px;
            text-align: center;
        }
        
        .header h1 {
            font-size: 2em;
            margin-bottom: 10px;
            font-weight: 700;
        }
        
        .header p {
            opacity: 0.9;
            font-size: 0.95em;
        }
        
        .progress-bar {
            display: flex;
            justify-content: space-between;
            padding: 30px 40px;
            background: #f8f9fa;
            border-bottom: 1px solid #e9ecef;
        }
        
        .progress-step {
            display: flex;
            flex-direction: column;
            align-items: center;
            position: relative;
            flex: 1;
        }
        
        .progress-step:not(:last-child)::after {
            content: '';
            position: absolute;
            top: 15px;
            left: 60%;
            width: 80%;
            height: 2px;
            background: #e9ecef;
        }
        
        .progress-step.active:not(:last-child)::after {
            background: #667eea;
        }
        
        .step-number {
            width: 30px;
            height: 30px;
            border-radius: 50%;
            background: #e9ecef;
            color: #6c757d;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: bold;
            font-size: 0.9em;
            margin-bottom: 8px;
            transition: all 0.3s ease;
            z-index: 1;
        }
        
        .progress-step.active .step-number {
            background: #667eea;
            color: white;
        }
        
        .progress-step.completed .step-number {
            background: #28a745;
            color: white;
        }
        
        .step-label {
            font-size: 0.85em;
            color: #6c757d;
            font-weight: 500;
        }
        
        .progress-step.active .step-label {
            color: #667eea;
            font-weight: 600;
        }
        
        .content {
            padding: 40px 30px;
        }
        
        .form-group {
            margin-bottom: 25px;
        }
        
        .form-group label {
            display: block;
            margin-bottom: 8px;
            color: #495057;
            font-weight: 600;
            font-size: 0.95em;
        }
        
        .form-group input {
            width: 100%;
            padding: 12px 15px;
            border: 2px solid #e9ecef;
            border-radius: 10px;
            font-size: 1em;
            transition: all 0.3s ease;
            font-family: inherit;
        }
        
        .form-group input:focus {
            outline: none;
            border-color: #667eea;
            box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);
        }
        
        .form-group small {
            display: block;
            margin-top: 5px;
            color: #6c757d;
            font-size: 0.85em;
        }
        
        .alert {
            padding: 15px 20px;
            border-radius: 10px;
            margin-bottom: 25px;
            font-size: 0.95em;
        }
        
        .alert-error {
            background: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
        }
        
        .alert-success {
            background: #d4edda;
            color: #155724;
            border: 1px solid #c3e6cb;
        }
        
        .btn {
            padding: 14px 30px;
            border: none;
            border-radius: 10px;
            font-size: 1em;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.3s ease;
            font-family: inherit;
        }
        
        .btn-primary {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            width: 100%;
        }
        
        .btn-primary:hover {
            transform: translateY(-2px);
            box-shadow: 0 5px 20px rgba(102, 126, 234, 0.4);
        }
        
        .btn-primary:disabled {
            opacity: 0.6;
            cursor: not-allowed;
            transform: none;
        }
        
        .success-message {
            text-align: center;
            padding: 30px 20px;
        }
        
        .success-icon {
            width: 80px;
            height: 80px;
            background: linear-gradient(135deg, #28a745 0%, #20c997 100%);
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            margin: 0 auto 25px;
            animation: scaleIn 0.5s ease-out;
        }
        
        @keyframes scaleIn {
            from {
                transform: scale(0);
            }
            to {
                transform: scale(1);
            }
        }
        
        .success-icon svg {
            width: 40px;
            height: 40px;
            fill: white;
        }
        
        .success-message h2 {
            color: #28a745;
            margin-bottom: 15px;
            font-size: 1.8em;
        }
        
        .success-message p {
            color: #6c757d;
            margin-bottom: 25px;
            line-height: 1.6;
        }
        
        .next-steps {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 10px;
            margin-top: 25px;
        }
        
        .next-steps h3 {
            color: #495057;
            margin-bottom: 15px;
            font-size: 1.1em;
        }
        
        .next-steps ul {
            list-style: none;
            padding: 0;
        }
        
        .next-steps li {
            padding: 8px 0;
            color: #6c757d;
            position: relative;
            padding-right: 25px;
        }
        
        .next-steps li::before {
            content: '✓';
            position: absolute;
            right: 0;
            color: #28a745;
            font-weight: bold;
        }
        
        .warning-box {
            background: #fff3cd;
            border: 1px solid #ffc107;
            border-radius: 10px;
            padding: 15px;
            margin-top: 20px;
            color: #856404;
            font-size: 0.9em;
        }
    </style>
</head>
<body>
    <div class="installer-container">
        <div class="header">
            <h1>🚀 نصب DomainHub</h1>
            <p>سیستم جستجو و ثبت دامنه‌های اینترنتی</p>
        </div>
        
        <div class="progress-bar">
            <div class="progress-step <?php echo $step >= 1 ? 'active' : ''; ?> <?php echo $step > 1 ? 'completed' : ''; ?>">
                <div class="step-number"><?php echo $step > 1 ? '✓' : '1'; ?></div>
                <div class="step-label">اتصال به دیتابیس</div>
            </div>
            <div class="progress-step <?php echo $step >= 2 ? 'active' : ''; ?> <?php echo $step > 2 ? 'completed' : ''; ?>">
                <div class="step-number"><?php echo $step > 2 ? '✓' : '2'; ?></div>
                <div class="step-label">ایجاد جداول</div>
            </div>
            <div class="progress-step <?php echo $step >= 3 ? 'active' : ''; ?>">
                <div class="step-number"><?php echo $step >= 3 ? '✓' : '3'; ?></div>
                <div class="step-label">پایان نصب</div>
            </div>
        </div>
        
        <div class="content">
            <?php if (!empty($errors)): ?>
                <div class="alert alert-error">
                    <strong>خطا:</strong>
                    <ul style="margin: 10px 0 0 20px;">
                        <?php foreach ($errors as $error): ?>
                            <li><?php echo htmlspecialchars($error); ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>
            
            <?php if ($step === 1): ?>
                <form method="POST">
                    <input type="hidden" name="step" value="1">
                    
                    <div class="form-group">
                        <label for="db_host">آدرس سرور دیتابیس (Host)</label>
                        <input type="text" id="db_host" name="db_host" value="<?php echo htmlspecialchars($_POST['db_host'] ?? 'localhost'); ?>" required>
                        <small>معمولاً localhost است</small>
                    </div>
                    
                    <div class="form-group">
                        <label for="db_port">پورت دیتابیس</label>
                        <input type="number" id="db_port" name="db_port" value="<?php echo htmlspecialchars($_POST['db_port'] ?? '3306'); ?>" required>
                        <small>پورت پیش‌فرض MySQL: 3306</small>
                    </div>
                    
                    <div class="form-group">
                        <label for="db_name">نام دیتابیس</label>
                        <input type="text" id="db_name" name="db_name" value="<?php echo htmlspecialchars($_POST['db_name'] ?? ''); ?>" required>
                        <small>در صورت عدم وجود، ساخته خواهد شد</small>
                    </div>
                    
                    <div class="form-group">
                        <label for="db_user">نام کاربری دیتابیس</label>
                        <input type="text" id="db_user" name="db_user" value="<?php echo htmlspecialchars($_POST['db_user'] ?? ''); ?>" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="db_pass">رمز عبور دیتابیس</label>
                        <input type="password" id="db_pass" name="db_pass" value="<?php echo htmlspecialchars($_POST['db_pass'] ?? ''); ?>">
                        <small>در صورت عدم نیاز خالی بگذارید</small>
                    </div>
                    
                    <button type="submit" class="btn btn-primary">
                        بررسی و ادامه
                    </button>
                </form>
                
            <?php elseif ($step === 2): ?>
                <div class="alert alert-success">
                    ✅ اتصال به دیتابیس با موفقیت انجام شد.
                </div>
                
                <form method="POST">
                    <input type="hidden" name="step" value="2">
                    <button type="submit" class="btn btn-primary">
                        ایجاد جداول و تکمیل نصب
                    </button>
                </form>
                
            <?php elseif ($step === 3): ?>
                <div class="success-message">
                    <div class="success-icon">
                        <svg viewBox="0 0 24 24">
                            <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/>
                        </svg>
                    </div>
                    <h2>نصب با موفقیت انجام شد!</h2>
                    <p>تبریک! DomainHub با موفقیت نصب شد. اکنون می‌توانید از سیستم استفاده کنید.</p>
                    
                    <div class="next-steps">
                        <h3>مراحل بعدی:</h3>
                        <ul>
                            <li>حذف فایل install.php برای امنیت بیشتر</li>
                            <li>ورود به پنل مدیریت با نام کاربری: admin و رمز: admin123</li>
                            <li>تغییر رمز عبور ادمین از پنل مدیریت</li>
                            <li>تنظیمات اولیه سیستم از پنل مدیریت</li>
                            <li>پیکربندی API Namecheap و سایر سرویس‌ها</li>
                        </ul>
                    </div>
                    
                    <div class="warning-box">
                        <strong>⚠️ هشدار امنیتی:</strong><br>
                        لطفاً پس از اطمینان از نصب صحیح، فایل <code>install.php</code> را از سرور حذف کنید.
                    </div>
                    
                    <div style="margin-top: 25px;">
                        <a href="index.php" class="btn btn-primary" style="display: inline-block; text-decoration: none;">
                            ورود به سایت
                        </a>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
</body>
</html>
